<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\CountryCaa $model
*/

$this->title = 'Country Caa ' . $model->country_id;
$this->params['breadcrumbs'][] = ['label' => 'Country Caas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->country_id, 'url' => ['view', 'country_id' => $model->country_id, 'caa_id' => $model->caa_id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="country-caa-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List', ['index'], ['class'=>'btn btn-default']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'country_id' => $model->country_id, 'caa_id' => $model->caa_id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
                        <?= $model->country_id ?>        </div>

        <div class="panel-body">



    <?php $this->beginBlock('app\models\CountryCaa'); ?>

    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'country_id',
    'value' => ($model->getCountry()->one() ? Html::a($model->getCountry()->one()->name, ['country/view', 'id' => $model->getCountry()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'caa_id',
    'value' => ($model->getCaa()->one() ? Html::a($model->getCaa()->one()->Name, ['caa/view', 'id' => $model->getCaa()->one()->id,]) : '<span class="label label-warning">?</span>'),
],
    ],
    ]); ?>

    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'country_id' => $model->country_id, 'caa_id' => $model->caa_id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> CountryCaa',
    'content' => $this->blocks['app\models\CountryCaa'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
